version: '3.8'

services:
  honeymail:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: honeymail
    ports:
      - "25:10025"   # SMTP port
      # - "10026:10026"   # SMTP TLS port
      # - "8080:8080"     # API port
    volumes:
      - ./mail.db:/app/mail.db
      - ./logs:/app/logs
      - ./conf:/app/conf
      - ./GeoLite2-City.mmdb:/app/GeoLite2-City.mmdb
    restart: unless-stopped
    environment:
      - TZ=UTC